---
language: node_js

node_js:
  - 0.10
  - 0.11
#  - iojs-v1

before_install:
  - npm install -g gulp

install:
  - npm install

script:
  - npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e15dcef52fad1be824f
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
